package main

SCREEN_WIDTH :: 1024
SCREEN_HEIGHT :: 768
MID_WIDTH :: SCREEN_WIDTH / 2
MID_HEIGHT :: SCREEN_HEIGHT / 2
STEP_SIZE :: 16
PLAYER_WIDTH :: 25
PLAYER_HEIGHT :: 25
SHOW_DEBUG :: false
DEBUG_NO_ENEMIES :: false
